# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN npm run build

# Use a new image for the runtime
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules

# Set environment variables
ENV PERPLEXITY_API_KEY="your-api-key-here" \
    PERPLEXITY_MODEL="sonar"

# Expose any ports if necessary (not specified in the README)
# EXPOSE 3000

# Command to run the application
CMD ["node", "build/index.js"]
